# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
minikube: false

namespace: "default"
replicaCount: 1
nodePort: 30001

app:
  port: 5000
  readinessProbeFailure: false
  livenessProbeFailure: false

image:
  repository: annalach/learning-summary-project-k8s-march-2023
  pullPolicy: IfNotPresent
  tag: ""
