import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { KubeConfig, CoreV1Api, V1PodStatus } from "@kubernetes/client-node";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

type Pod = {
  name: string;
  ready: string;
  status: string;
  age: string;
};

type Props = {
  pods: Pod[];
};

export default function Home(props: Props): JSX.Element {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.tsx</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{" "}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>
        <div className={styles.center}>
          <table>
            <thead>
              <tr>
                <th>Name</th>
                <th>Ready</th>
                <th>Status</th>
                <th>Age</th>
              </tr>
            </thead>
            <tbody>
              {props.pods.map(({ name, status, ready, age }) => (
                <tr key={name}>
                  <td>{name}</td>
                  <td>{ready}</td>
                  <td>{status}</td>
                  <td>{age}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  );
}

type ServerSideProps = {
  props: Props;
};

export async function getServerSideProps(): Promise<ServerSideProps> {
  const kc = new KubeConfig();
  kc.loadFromDefault();

  const k8sApi = kc.makeApiClient(CoreV1Api);

  const response = await k8sApi.listNamespacedPod(process.env.NAMESPACE!);
  const pods = response.body.items.map(({ metadata, status: podStatus }) => {
    const ready = getReady(podStatus);
    const status = getStatus(podStatus);
    const age = getAge(Date.now(), podStatus?.startTime);

    return {
      name: metadata?.name!,
      ready,
      status,
      age,
    };
  });

  return {
    props: {
      pods,
    },
  };
}

function getReady(podStatus?: V1PodStatus): string {
  if (!podStatus || !podStatus.containerStatuses) {
    return "";
  }

  return `${podStatus?.containerStatuses?.reduce(
    (previousValue, currentValue) => {
      if (currentValue.ready) {
        return previousValue + 1;
      }
      return previousValue;
    },
    0
  )} /
  ${podStatus?.containerStatuses?.length}`;
}

function getStatus(podStatus?: V1PodStatus): string {
  if (!podStatus) {
    return "";
  }

  const containerStatusesSummary =
    (podStatus?.containerStatuses?.some(({ state }) => state?.waiting) &&
      podStatus?.containerStatuses?.reduce((previousValue, currentValue) => {
        if (currentValue.state?.waiting) {
          return currentValue.state?.waiting?.reason || previousValue;
        }
        return previousValue;
      }, "")) ||
    podStatus?.phase;

  return containerStatusesSummary || "";
}

function getAge(currentTimeInEpoch: number, startTime?: Date): string {
  if (!startTime) {
    return "";
  }

  const timeDiffInMilliseconds = currentTimeInEpoch - startTime.getTime();
  const timeDiffInSeconds = Math.floor(timeDiffInMilliseconds / 1000);

  const seconds = timeDiffInSeconds % 60;
  const secondsAsString = seconds < 10 ? `0${seconds}` : seconds;

  const timeDiffInMinutes = Math.floor(timeDiffInSeconds / 60);

  const minutes = timeDiffInMinutes % 60;
  const minutesAsString = minutes < 10 ? `0${minutes}` : minutes;

  const hours = Math.floor(timeDiffInMinutes / 60);
  const hoursAsString = hours < 10 ? `0${hours}` : hours;

  if (hoursAsString === "00" && minutesAsString === "00") {
    return `${secondsAsString}s`;
  }

  if (hoursAsString === "00") {
    return `${minutesAsString}m${secondsAsString}s`;
  }

  return `${hoursAsString}h${minutesAsString}m${secondsAsString}s`;
}
