import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { KubeConfig, CoreV1Api } from "@kubernetes/client-node";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

type Pod = {
  name: string;
  ready: string;
  status: string;
  age: string;
};

type Props = {
  pods: Pod[];
};

export default function Home(props: Props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.tsx</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{" "}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>
        <div className={styles.center}>
          <table>
            <thead>
              <tr>
                <th>Name</th>
                <th>Ready</th>
                <th>Status</th>
                <th>Age</th>
              </tr>
            </thead>
            <tbody>
              {props.pods.map(({ name, status, ready, age }) => (
                <tr key={name}>
                  <td>{name}</td>
                  <td>{ready}</td>
                  <td>{status}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const kc = new KubeConfig();
  kc.loadFromDefault();

  const k8sApi = kc.makeApiClient(CoreV1Api);

  const response = await k8sApi.listNamespacedPod(process.env.NAMESPACE!);
  console.log(JSON.stringify(response.body.items[0]));
  const pods = response.body.items.map(({ metadata, status }) => {
    const ready = `${status?.containerStatuses?.reduce(
      (previousValue, currentValue) => {
        if (currentValue.ready) {
          return previousValue + 1;
        }
        return previousValue;
      },
      0
    )} /
    ${status?.containerStatuses?.length}`;

    const containerStatusesSummary =
      (status?.containerStatuses?.some(({ state }) => state?.waiting) &&
        status?.containerStatuses?.reduce((previousValue, currentValue) => {
          if (currentValue.state?.waiting) {
            return currentValue.state?.waiting?.reason || previousValue;
          }

          return previousValue;
        }, "")) ||
      status?.phase;

    return {
      name: metadata?.name,
      ready,
      status: containerStatusesSummary,
      age: "",
    };
  });

  return {
    props: {
      pods,
    },
  };
}
