apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "names.configMap" . }}
  namespace: {{ .Values.namespace }}
  labels: {{- include "labels.standard" . | nindent 4 }}
data:
  PORT: {{ .Values.app.port | quote }}
  READINESS_PROBE_FAILURE: {{ .Values.app.readinessProbeFailure | quote }}
  LIVENESS_PROBE_FAILURE: {{ .Values.app.livenessProbeFailure | quote }}
  NAMESPACE: {{ .Values.namespace | quote }}
