apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.deployment" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "common.names.appName" . }}
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ include "common.names.appName" . }}
    spec:
      containers:
      - name: {{ include "common.names.appName" . }}
        image: myapp:v0.1.0
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: {{ include "common.names.envVars" . }}
        resources: {}
