apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.deployment" . }}
  namespace: {{ .Values.namespaces }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "common.names.appName" . }}
  strategy: {}
  template:
    metadata:
      annotations:
        # https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app: {{ include "common.names.appName" . }}
    spec:
      initContainers:
      - name: alpine
        image: alpine:3.17
        command: ["sleep"] # entrypoint
        args: ["60"]       # arguments to the entrypoint
      containers:
      - name: {{ include "common.names.appName" . }}
        image: myapp:{{ .Chart.AppVersion }}
        resources:
          requests:
            memory: "64Mi"  # 64 mebibytes
            cpu: "250m"     # 1/4 (v)CPU
          limits:
            memory: "128Mi" # 128 mebibytes
            cpu: "500m"     # 1/2 (v)CPU
        readinessProbe:
          httpGet:
            path: /api/ready
            port: {{ .Values.app.port }}
          initialDelaySeconds: 20
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /api/healthy
            port: {{ .Values.app.port }}
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: {{ include "common.names.envVars" . }}
