apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp
  name: {{ include "common.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "common.name" . }}
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ include "common.name" . }}
    spec:
      containers:
      - name: {{ include "common.name" . }}
        image: myapp:v0.1.0
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: myapp-configmap
        resources: {}
