apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "name.role" . }}
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "name.serviceAccount" . }}
roleRef:
  kind: Role
  name: {{ include "name.role" . }}
  apiGroup: rbac.authorization.k8s.io
