apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "names.role" . }}
  labels: {{- include "labels.standard" . | nindent 4 }}
rules:
- apiGroups: [""] # Core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
