apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "name.role" . }}
rules:
- apiGroups: [""] # Core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
