apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "names.role" . }}
  namespace: {{ .Values.namespace }}
  labels: {{- include "labels.standard" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "names.serviceAccount" . }}
roleRef:
  kind: Role
  name: {{ include "names.role" . }}
  apiGroup: rbac.authorization.k8s.io
