apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels: {{- include "labels.standard" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: {{ .Values.app.port }}
    protocol: TCP
    targetPort: {{ .Values.app.port }}
    {{- if .Values.minikube }}
    nodePort: {{ .Values.nodePort }}
    {{- end }}
  selector: {{- include "labels.matchLabels" . | nindent 4 }}
  type: {{ if .Values.minikube }}NodePort{{ else }}ClusterIP{{ end }}
