apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-service
  name: my-service
spec:
  ports:
  - name: {{ .Values.app.port }}-{{ .Values.app.port }}
    port: {{ .Values.app.port }}
    protocol: TCP
    targetPort: {{ .Values.app.port }}
    nodePort: {{ .Values.nodePort }}
  selector:
    app: {{ include "common.name" . }}
  type: NodePort
