apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.service" . }}
spec:
  ports:
  - name: {{ .Values.app.port }}-{{ .Values.app.port }}
    port: {{ .Values.app.port }}
    protocol: TCP
    targetPort: {{ .Values.app.port }}
    nodePort: {{ .Values.nodePort }}
  selector:
    app: {{ include "common.names.appName" . }}
  type: {{ if .Values.minikube }}NodePort{{ else }}ClusterIP{{ end }}
