apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.service" . }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: {{ .Values.app.port }}-{{ .Values.app.port }}
    port: {{ .Values.app.port }}
    protocol: TCP
    targetPort: {{ .Values.app.port }}
    {{- if .Values.minikube }}
    nodePort: {{ .Values.nodePort }}
    {{- end }}
  selector:
    app: {{ include "common.names.appName" . }}
  type: {{ if .Values.minikube }}NodePort{{ else }}ClusterIP{{ end }}
