apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: {{ .Values.app.port }}-{{ .Values.app.port }}
    port: {{ .Values.app.port }}
    protocol: TCP
    targetPort: {{ .Values.app.port }}
    {{- if .Values.minikube }}
    nodePort: {{ .Values.nodePort }}
    {{- end }}
  selector:
    {{- include "labels" . | indent 4 }}
  type: {{ if .Values.minikube }}NodePort{{ else }}ClusterIP{{ end }}
